version: '3.9'

services:
  music_downloader:
    build:
      context: ./services/music_downloader
    ports:
      - "5001:5001"
    volumes:
      - ./services/music_downloader/downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - music_downloader
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development